FROM node:23.11-slim

WORKDIR /app

# RUN npm install -g @angular/cli

# COPY . .

# RUN npm ci

# # Using 0.0.0.0 to allow external connections
# CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "80"]
