user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;

        client_max_body_size 100M;
        client_body_timeout 300s;

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        include /etc/nginx/conf.d/*.conf;
    }
}