function(find_files RESULT SEARCH_PATH EXTENSION)
  file(GLOB_RECURSE FILES "${SEARCH_PATH}/*.${EXTENSION}")
  set(FILTERED_FILES "")
  
  foreach(FILE ${FILES})
    get_filename_component(FILE_DIR ${FILE} DIRECTORY)
    get_filename_component(DIR_NAME ${FILE_DIR} NAME)
    
    if(NOT DIR_NAME STREQUAL "include")
      list(APPEND FILTERED_FILES ${FILE})
    endif()
  endforeach()
  
  set(${RESULT} ${FILTERED_FILES} PARENT_SCOPE)
endfunction()

function(find_includes RESULT SEARCH_PATH)
  file(GLOB_RECURSE FILES "${SEARCH_PATH}/*")
  set(INCLUDES_DIR "")
  foreach(FILE ${FILES})
    get_filename_component(FILE_DIR ${FILE} DIRECTORY)
    get_filename_component(DIR_NAME ${FILE_DIR} NAME)
    if(DIR_NAME STREQUAL "include")
      list(APPEND INCLUDES_DIR ${FILE_DIR})
    endif()
  endforeach()
  list(REMOVE_DUPLICATES INCLUDES_DIR)
  set(${RESULT} ${INCLUDES_DIR} PARENT_SCOPE)
endfunction()

function(find_headers RESULT SEARCH_PATH)
  file(GLOB_RECURSE FILES "${SEARCH_PATH}/*.h")
  set(FILTERED_FILES "")
  
  foreach(FILE ${FILES})
    get_filename_component(FILE_DIR ${FILE} DIRECTORY)
    
    list(APPEND HEADER_FILES ${FILE})
  endforeach()
  
  set(${RESULT} ${HEADER_FILES} PARENT_SCOPE)
endfunction()

function(cmake_include_services)
    set(SRC_DIR "${PROJECT_SOURCE_DIR}/src")
    file(GLOB SRC_SUBDIRS RELATIVE "${SRC_DIR}" "${SRC_DIR}/*")
    foreach(SUBDIR ${SRC_SUBDIRS})
        set(FULL_SUBDIR_PATH "${SRC_DIR}/${SUBDIR}")
        
        if(IS_DIRECTORY "${FULL_SUBDIR_PATH}")
            include("${FULL_SUBDIR_PATH}/CMakeLists.txt")
            message(STATUS "  ${FULL_SUBDIR_PATH}")
        endif()
    endforeach()
endfunction()