function(FindCXXFiles RESULT SEARCH_PATH)
  file(GLOB_RECURSE FILES "${SEARCH_PATH}/*.cpp")
  set(FILTERED_FILES "")
  
  foreach(FILE ${FILES})
    get_filename_component(FILE_DIR ${FILE} DIRECTORY)
    get_filename_component(DIR_NAME ${FILE_DIR} NAME)
    
    if(NOT DIR_NAME STREQUAL "include")
      list(APPEND FILTERED_FILES ${FILE})
    endif()
  endforeach()
  
  set(${RESULT} ${FILTERED_FILES} PARENT_SCOPE)
endfunction()

function(FindIncludes RESULT SEARCH_PATH)
  file(GLOB_RECURSE FILES "${SEARCH_PATH}/*")
  set(INCLUDES_DIR "")
  foreach(FILE ${FILES})
    get_filename_component(FILE_DIR ${FILE} DIRECTORY)
    get_filename_component(DIR_NAME ${FILE_DIR} NAME)
    if(DIR_NAME STREQUAL "include")
      list(APPEND INCLUDES_DIR ${FILE_DIR})
    endif()
  endforeach()
  list(REMOVE_DUPLICATES INCLUDES_DIR)
  set(${RESULT} ${INCLUDES_DIR} PARENT_SCOPE)
endfunction()