services:
  microservice:
    image: gcc:latest
    working_dir: /app
    env_file:
      - ../../.env
    container_name: ${SERVICE_NAME}
    environment:
      - SERVICE_NAME=${SERVICE_NAME}
    networks:
      - app-network
    volumes:
      - ../src/${SERVICE_NAME}:/app/src/${SERVICE_NAME}
      - ../lib:/app/lib
      - ../cmake:/app/cmake
      - ../setup:/app/setup
      - ../CMakeLists.txt:/app/CMakeLists.txt
    restart: unless-stopped
    command: > 
      bash -c "
      apt-get update;
      apt-get install -y git cmake build-essential libssl-dev libsasl2-dev libpq-dev pkg-config;
      mkdir -p build;
      cd build;
      cmake -DCMAKE_BUILD_TYPE=Release -DSERVICE_NAME=${SERVICE_NAME} ..;
      cmake --build . --parallel $$(nproc);
      ./${SERVICE_NAME}"
networks:
  app-network:
    external: true